# After updating versions file, run tools/calc-hashes.sh script

SUMMIT_60_RADIO_STACK_VERSION_VALUE      = 13.0.0.22
SUMMIT_BDSDMAC_RADIO_STACK_VERSION_VALUE = 13.0.0.22
SUMMIT_LWB_RADIO_STACK_VERSION_VALUE     = 13.0.0.22
SUMMIT_MSD_RADIO_STACK_VERSION_VALUE     = 13.0.0.22
SUMMIT_NX_RADIO_STACK_VERSION_VALUE      = 13.0.0.22
SUMMIT_TI_RADIO_STACK_VERSION_VALUE      = 13.0.0.22
