#!/bin/sh

# Allow a few customizations from a config file
test -r /etc/default/NetworkManager && . /etc/default/NetworkManager

PID=$(pidof NetworkManager)
case "${1}" in
	start)
		printf "Starting NetworkManager ... "
		[ -d /var/run/NetworkManager ] || install -d /var/run/NetworkManager
		[ -n "${PID}" ] && /usr/sbin/NetworkManager ${NETWORKMANAGER_ARGS} && \
			echo "done." || echo "failed!"
		;;
	stop)
		printf "Stopping NetworkManager ... "
		[ -n "${PID}" ] && kill "${PID}" > /dev/null 2>&1 && \
			echo "done." || echo "failed!"
		;;
	restart)
		${0} stop
		sleep 1
		${0} start
		;;
	*)
		echo "usage: ${0} {start|stop|restart}"
		;;
esac
