ifneq ($(BR2_LRD_DEVEL_BUILD),y)

SUMMIT_MFG611_VERSION = $(SUMMIT_NX_RADIO_STACK_VERSION_VALUE)
SUMMIT_MFG611_SOURCE = mfg611-$(SUMMIT_RADIO_STACK_ARCH)-$(SUMMIT_MFG611_VERSION).tar.bz2
SUMMIT_MFG611_STRIP_COMPONENTS = 0
SUMMIT_MFG611_LICENSE = Ezurio
SUMMIT_MFG611_LICENSE_FILES = LICENSE.ezurio
SUMMIT_MFG611_EXT = _611

ifeq ($(MSD_BINARIES_SOURCE_LOCATION),laird_internal)
SUMMIT_MFG611_SITE = $(SUMMIT_RADIO_URI_BASE_INTERNAL)/mfg611/laird/$(SUMMIT_MFG611_VERSION)
else ifeq ($(MSD_BINARIES_SOURCE_LOCATION),local)
  SUMMIT_MFG611_VERSION = 0.$(BR2_SUMMIT_BRANCH).0.0
  BR_NO_CHECK_HASH_FOR += $(SUMMIT_MFG611_SOURCE)
  SUMMIT_MFG611_SITE = file://$(BASE_DIR)/../mfg611-$(SUMMIT_RADIO_STACK_ARCH)/images
else ifneq ($(SUMMIT_SOM_URI_BASE_ARCHIVE),)
SUMMIT_MFG611_SITE = $(SUMMIT_SOM_URI_BASE_ARCHIVE)-$(SUMMIT_MFG611_VERSION)
else
SUMMIT_MFG611_SITE = $(SUMMIT_RADIO_URI_BASE_611)-$(SUMMIT_MFG611_VERSION)
endif

define SUMMIT_MFG611_POST_EXTRACT
	(cd $(@D) && ./$(SUMMIT_MFG611_SOURCE:%.tar.bz2=%.sh) tar)
	tar -xvjf $(@D)/$(SUMMIT_MFG611_SOURCE) -C $(@D)
	rm $(@D)/$(SUMMIT_MFG611_SOURCE) $(@D)/$(SUMMIT_MFG611_SOURCE:%.tar.bz2=%.sh) $(@D)/$(SUMMIT_MFG611_SOURCE:%.tar.bz2=%.sha)
endef

SUMMIT_MFG611_POST_EXTRACT_HOOKS += SUMMIT_MFG611_POST_EXTRACT

ifeq ($(BR2_PACKAGE_SUMMIT_MFG611_LMU),y)
define SUMMIT_MFG611_LMU_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 755 -t $(TARGET_DIR)/usr/bin  $(@D)/lmu$(SUMMIT_MFG611_EXT)
endef
endif

define SUMMIT_MFG611_INSTALL_TARGET_CMDS
	$(SUMMIT_MFG611_LMU_INSTALL_TARGET_CMDS)
endef

endif

$(eval $(generic-package))
